version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ifrn@2025
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: ifrn@2025
    
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: localhost:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: ifrn@2025
      WORPRESS_DB_NAME: wordpress_db
    volumes:
      - wp_data:/var/www/html

volumes:
  db_data: {}
  wp_data: {}
